create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  username text unique not null,
  email text unique not null,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  title text not null,
  content text not null,
  horse text,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.predictions enable row level security;
